qualcomm-linux/meta-qcom-hwe

- ci/base.yml
- ci/qcm6490-idp.yml
- ci/qcs6490-rb3gen2-core-kit.yml
- ci/sa8775p-ride-sx.yml
Kas files covering the 3 initial machine configurations available as part of this layer.
Initial CI runs will cover local main plus latest revision from all the layer dependencies, using poky as distro.
meta-qcom-distro will be tested as part of the meta-qcom-distro layer.
> ci: add initial kas files for the expected ci jobs

- conf/layer.conf
Minor fixes for layer.conf, aligning the layer priority to the base layers (and other bsp layers) and also making the dependency on oe-core explicit.
> layer.conf: decrease priority, depend on OE-Core and move to styhead

- conf/layer.conf
On kirkstone branch BBFILE_COLLECTIONS set to 'qcom-hwe'. Use the same on main branch as well to have consistency while referring this layer in other meta layers.
> conf/layer.conf: Update BBFILE_COLLECTIONS

- .github/workflows/check-layer.yml
- ci/yocto-check-layer.sh
Add the yocto-check-layer with a script to be easy to replicate locally.
Also change:
- add --no-auto
It is required if kas runs inside the bsp layer. So to make the yocto-check-layer
happy whether it runs inside or outside it is better to have this arg.
- use the base.yml
The --machines can be used when we need to check the layer with one or more machines.
By default the machine is not required because the yocto-check-layer-wrapper run's
on a clean build dir.
> ci: add yocto-check-layer helper script

- README.md
Update README.md to reflect the new development process for the main branch (with a note about kirkstone), with additional information about the new contribution guidelines.
Removed meta-qcom-distro related information as it is out of scope of this repository (BSP only).
> README: revamp readme to reflect main and the development process

- .github/workflows/repolinter.yml
- ci/yocto-check-layer.sh
Adds [Repolinter](https://github.com/todogroup/repolinter) checks to PRs and pushes to main. Repoliner is a TODO Group (Linux Foundation) created project that lints for common open source repo issues. 
The [config](https://github.com/quic/.github/blob/main/repolint.json) is pulled from our main QuIC org, but if we need to override we can [extend and configure it locally](https://github.com/quic/.github/tree/main?tab=readme-ov-file#customizing-repolinter-rules).
Let me know if any concerns with enabling this check on this repo. Also, should we enable for other repos such as qcom distro?
> Enable Repolinter checks on main

- .github/workflows/build-yocto.yml
- ci/base.yml
- ci/mirror.yml
There are situations when the upstream hash equivalent server is
not available or even if its use is not desired.
> disable sstate-cache mirror by default

- ci/qcm6490.yml
- ci/qcs6490-rb3gen2-core-kit.yml
esp-qcom-image needs to be built in addition to core-image-minimal in order to have both ESP and rootfs.
> ci: qcm6490: build both esp-qcom-image and core-image-minimal images

- conf/machine/include/qcom-qcs9100.inc
The value of the SOC_FAMILY is not expected to change so assing it directly.
> qcom-qcs9100: don't weak assignment SOC_FAMILY

- .github/workflows/build-yocto.yml
- .github/workflows/nightly-build.yml
- .github/workflows/repolinter.yml
I noticed my doanac/meta-qcom-hwe fork was trying to run this cron job every night but fails because there is no runner for it.
> ci: Only do cron job on main repository

- .github/workflows/build-yocto.yml
- .github/workflows/nightly-build.yml
Reusing the build-yocto workflow since it has everything we need and avoids duplication of code.
Ref https://docs.github.com/en/actions/sharing-automations/reusing-workflows
> ci: nightly-build: use the build-yocto

- .github/workflows/build-yocto.yml
- ci/mirror.yml
Yocto upstream switched to a new server for the scarthgap
release and now the mirror is listening using websockets.
Reference: https://git.yoctoproject.org/poky/commit/?id=632e3170595bb32717c0471a55a619b4b33fe787
> ci/mirror: Fix hashequivalence server address 

- .github/workflows/build-yocto.yml
The main change is the 2nd one, where we clone all kas repos in our persistent storage to avoid cloning each time from upstream. This variable needed to be global so that it's used in all jobs (kas-dump, check-layer and compile) since they all today clone all repos from upstream.
Since I was adding global env variables, I also added one for the persistent folder, since it was used in 2 different places already.
> Kas persistent

- conf/machine/sa8775p-ride-sx.conf
Adding qcom-adreno-a663 linux
firmware packages to sa7885p ride board
> conf/machine: add firmware package to sa7885p ride board

- conf/machine/qcm6490-idp.conf
- conf/machine/qcs6490-rb3gen2-core-kit.conf
Adding qcom-qcm6490-{audio, compute} firmware packages
to qcm6490-idp.conf and qcs6490-rb3gen2-core-kit.conf 
to add support of adsp and cdsp firmware
> rb3gen2-corekit, idp confs: add firmware packages

- conf/machine/include/qcom-qcs6490.inc
- conf/machine/include/qcom-qcs9100.inc
- recipes-bsp/partition/qcom-partition-confs/qcm6490-partitions.conf
- recipes-bsp/partition/qcom-partition-confs/qcs9100-partitions.conf
- recipes-bsp/partition/qcom-partition-confs_1.0.bb
- recipes-devtools/partition-utils/qcom-gen-partition-bins_1.0.bb
- recipes-devtools/partition-utils/qcom-gen-partitions-tool/gen_partition.py
- recipes-devtools/partition-utils/qcom-gen-partitions-tool_1.0.bb
- recipes-devtools/partition-utils/qcom-ptool/0001-ptool.py-Generate-zero-files-in-output-folder-when-s.patch
- recipes-devtools/partition-utils/qcom-ptool/0002-ptool.py-Python-3-support.patch
- recipes-devtools/partition-utils/qcom-ptool_git.bb
Forward port from kirkstone (qclinux 1.2) the recipes required for generating machine specific partitioning files.
This is enough to have a working partition.xml and respective rawprogram/patch .xml files.
> Forward port recipes required for generating machine specific partitioning files

- conf/machine/qcs6490-rb3gen2-core-kit.conf
- recipes-kernel/linux/linux-yocto-dev.bbappend
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0001-arm64-dts-qcom-sc7280-don-t-enable-GPU-on-unsupporte.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-drivers/0001-firmware-qcom-scm-Introduce-CP_SMMU_APERTURE_ID.patch
- recipes-kernel/linux/linux-yocto-dev/qcm6490-drivers/0002-drm-msm-adreno-Setup-SMMU-aparture-for-per-process-p.patch
Pick up necessary patches and pull in firmware to enable GPU support on RB3Gen2 and QCM6490 IDP boards.
By default, even without these patches, drm/msm will attempt to bootstrap the GPU, but will fail because of the missing firmware.
> Fix GPU support on RB3Gen2 and QCM6490 IDP

- README.md
oss.qualcomm.com is preferred instead of quicinc.com.
> README: update my email to oss.qualcomm.com

- recipes-kernel/linux/linux-yocto-dev.bbappend
- recipes-kernel/linux/linux-yocto-dev/qcm6490-board-dts/0001-arm64-dts-qcom-qcm6490-idp-Add-UFS-nodes.patch
- recipes-kernel/linux/linux-yocto-dev/workarounds/0001-PENDING-arm64-dts-qcom-Remove-voltage-vote-support-f.patch
The change described in the patch isn't pending, but it has been rejected upstream. Use correct Upstream-Status for the patch.
> linux-yocto-dev: fix Upstream-Status for the UFS voltage patch

- ci/yocto-check-layer.sh
When running yocto-check-layer, we can see the following logs:
INFO: test_machine_signatures (bsp.BSPCheckLayer)
INFO:  ... skipped 'No machines set with --machines.'
INFO: No machines set with --machines.
INFO: test_machine_world (bsp.BSPCheckLayer)
INFO:  ... skipped 'No machines set with --machines.'
INFO: No machines set with --machines.
Because we do not set --machines when running the script, it does not try to run the tests with each individual machine. When setting machines, yocto-check-layer will ensure that all signatures do not change when setting MACHINE for each our supported machine. So we can catch more errors. Note that this is also what would be done by Yocto if we wanted to run the compliance tests.
E.g. from Yocto docs:
bsp.test_machine_world: Verifies that bitbake …
> ci: yocto-check-layer: set BSP machines to be tested

- conf/machine/include/qcom-qcs9100.inc
- recipes-bsp/firmware/firmware-qcom-boot-common.inc
- recipes-bsp/firmware/firmware-qcom-boot-qcs6490_00005.0.bb
- recipes-bsp/firmware/firmware-qcom-boot-qcs9100_00006.0.bb
Add the boot firmware package to install boot binaries for the QCS9100 based boards.
While at it, consolidate common code into firmware-qcom-boot-common.inc to avoid repetition.
> Add boot firmware package support for QCS9100

- ci/yocto-patchreview.sh
When a patch is malformed, the patchreview script can run a git blame command on the patch to provide additional contextual data. The --blame command was failing, and a fix was found, now that this patch is merged in poky:
79ef781499f5 (scripts: patchreview: fix failure when running from a different folder)
we can enable --blame in our script.
> ci: yocto-patchreview: run blame command to get additional context

- .github/workflows/build-yocto.yml
For some reasons, kas does not checkout what we expect. The lock yaml files contain the most recent commits from poky and meta-qcom, which is expected since we run kas dump --update, however the downstream kas commands checkout the latest commits in the local mirror, not what we set in the lock files.
Let's add some debug to observe what is happening during the build.
> ci: yocto-check-layer: run KAS with debug

- recipes-bsp/firmware/firmware-qcom-boot-qcs6490_00005.0.bb
- recipes-bsp/firmware/firmware-qcom-boot-qcs9100_00006.0.bb
The boot firmware files published by Qualcomm, even if they are versioned properly, are pusblished as
<platform>_bootbinaries.zip. Bitbake expects the version to be there in the downloaded filenames, since all downloads are placed in the same location (DL_DIR). As such installing different versions of the boot binaries will override them each time, and bitbake complains about that (and it causes unnecessary warnings and re-fetch).
We can customize the download file name using the 'downloadfilename' attribute in SRC_URI. With this patch, the firmware is downloaded as:
downloads/QCM6490_bootbinaries_r1.0_00005.0.zip
> firmware: set the download filename

- conf/layer.conf
This gets us slightly more deterministic behaviour since most layers, inclusing OE-core, set it to 5. When priorities are equal, the ordering in BBLAYERS is used to resolve conflicts. Since this layer was at '5', getting the ordering wrong would negate .bbappends and shadowed recipes.
Upstream bitbake wants to phase this out, but for the time being, let's decrease the opportunities for users to get this wrong.
Fixes: https://github.com/quic-yocto/meta-qcom-hwe/issues/98
> layer.conf: increase BBFILE_PRIORITY to 6

- .github/workflows/nightly-build.yml
When calling reusable workflow the secrets are not passed by default. This patch fixes the issue of missing LAVA token.
> workflows: pass secret in nightly build

- .github/workflows/build-yocto.yml
The file server now has a way to stream progress if the client side has logic. This should help with 2 things:
* better live debug
* less 503 errors that happen due to the server taking too long to deliver its status code
> ci: Update upload logic to use new streaming support

- README.md
Update organization name in the URLs (`s/quic-yocto/qualcomm-linux/g`).
> README.md: update organization in urls

- README.md
1. Address markdown style issues reported by the linter
2. Add initial flash instructions for Qualcomm® RB3 Gen 2 Development Kit.
> README: fix style issues/add flash instructions

- classes-recipe/image_types_qcom.bbclass
- recipes-bsp/firmware/firmware-qcom-boot-common.inc
- recipes-bsp/firmware/firmware-qcom-boot-qcs6490_00005.0.bb
- recipes-bsp/firmware/firmware-qcom-boot-qcs9100_00006.0.bb
- recipes-bsp/partition/qcom-partition-confs_1.0.bb
It was a bit more convoluted than I wanted.. but here is some initial support for flashing the CDT file.
The CDT file contains some IDs that are used at runtime to identify the board. The CDT is typically flashed in production on the device. However it is possible to erase/corrupt the CDT, which generally bricks the board. 
The CDT is published for some devices, at least all flavor of RB3 Gen2. This PR makes changes in every place where it's needed, so that the generated qcomflash package includes the CDT file, and the rawprogram XML file has the instructions to flash it. 
There are a few tricks in there..
1. The CDT is published in a non-versioned URL. This might be fixed later, for now we use downloadfilename attribute, to mitigate that.
2. the firmware recipes are SOC specific, however …
> Introduce CDT support

- .github/workflows/build-yocto.yml
- .github/workflows/nightly-build.yml
- .github/workflows/pr.yml
- .github/workflows/push.yml
- .github/workflows/test-pr.yml
- .github/workflows/test.yml
- ci/lava/qcs6490-rb3gen2-core-kit/boot.yaml
This patch splits the build and test workflows into separate files. Both workflows are now reusable. On top of that nightly-build, push and pr workflows are added. These correspond to individual triggers provided by github. Test can now be executed on the PR builds using additional workflow test-pr. This workflow is executed using worflow_run trigger and uses the meta-qcom-hwe repository context so required variables are available.
Fixes: #105
> workflows: refactor job and triggers

- .github/workflows/pr.yml
- .github/workflows/test-pr.yml
- .github/workflows/test.yml
This patch adds test reporting action to all workflows that executed testing. Reporiting is using existing action from marketplace: https://github.com/EnricoMi/publish-unit-test-result-action The action uses JUNIT formatted XML files as a base for the test results. PRs that trigger testing will also receive a comment with test result summary.
> workflows: add test reporting

- .github/workflows/nightly-build.yml
- .github/workflows/pr.yml
- .github/workflows/push.yml
- .github/workflows/test-pr.yml
Test reporting action requires the following permissions:
checks: write
pull-requests: write
This patch adds the required permissions to all jobs that require test reporting. In addition the following permissions are defined:
contents: read
packages: read
These are default values set by github, but need to be manually defined to prevent setting them to "none" as per actions documentation.
> workflows: update job permissions for test reporting

- classes/linux-qcom-bootimg.bbclass
- classes/linux-qcom-dtbbin.bbclass
- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife/ath10k-generate-board-2_json.sh
- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife/ath10k-generate-pci-board-2_json.sh
- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife/ath11k-generate-ahb-board-2_json.sh
- recipes-devtools/qca-swiss-army-knife/qca-swiss-army-knife/ath11k-generate-pci-board-2_json.sh
- recipes-support/fastrpc/fastrpc/mount-dsp.sh
- recipes-support/initrdscripts/files/copy-modules.sh
Add missing license / copyright declaration on scripts and bbclass files, needed by repolinter (and a standard practice in OE).
> Add missing license and copyright declaration needed by repolinter
